export type ActiveNotificationItem = {
  key: string;
  title: string;
  audience: string;
  trigger: string;
  category: "Transactional" | "Discovery" | "Reminder" | "Promo" | "System";
};

/** Catalog of notification types currently active in the product. */
export const ACTIVE_NOTIFICATIONS: ActiveNotificationItem[] = [
  {
    key: "PROFILE_ACTIVE",
    title: "Profile activated",
    audience: "User",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "PROFILE_SUSPEND",
    title: "Profile suspended",
    audience: "User",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "GET_AN_TEAM_JOINING_INVITATION_FROM_MEDIATOR",
    title: "Team invitation received",
    audience: "Worker",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "TEAM_JOINING_INVITATION_CANCELLERD_BY_MEDIATOR",
    title: "Team invitation cancelled",
    audience: "Worker",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "REMOVED_FROM_TEAM_BY_MEDIATOR",
    title: "Removed from team",
    audience: "Worker",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "ACCEPTED_TEAM_JOINING_REQUEST_BY_WORKER",
    title: "Worker accepted team invite",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "REJECTED_TEAM_JOINING_REQUEST_BY_WORKER",
    title: "Worker rejected team invite",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "WOREKR_LEFT_FROM_TEAM",
    title: "Worker left team",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "NEW_SERVICE_LIVE",
    title: "New work live",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Discovery",
  },
  {
    key: "NEW_SERVICE_ARRIVED_OF_SKILL",
    title: "Skill-matched work",
    audience: "Worker / Mediator",
    trigger: "Immediate + Hourly digest",
    category: "Discovery",
  },
  {
    key: "APPLIED_IN_YOUR_SERVICE",
    title: "Someone applied on your work",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SELECTED_IN_SERVICE",
    title: "Selected for work",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "REJECTED_FROM_SERVICE",
    title: "Application rejected",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "REMOVE_YOUR_SELECTION_FROM_SERVICE_BY_EMPLOYER",
    title: "Removed from work",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SELECTED_AS_MEDIATOR",
    title: "Selected as mediator",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "REJECTED_AS_MEDIATOR",
    title: "Rejected as mediator",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "REMOVE_YOUR_SELECTION_AS_MEDIATOR",
    title: "Removed as mediator",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "YOU_HAVE_BEEN_APPLIED_BY_MEDIATOR",
    title: "Mediator applied for you",
    audience: "Worker",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "YOU_HAVE_APPLIED_AS_A_MEDIATOR",
    title: "Mediator application received",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "MEDIATOR_CANCELLED_APPLICATION",
    title: "Mediator cancelled application",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "WORKER_CANCELLED_APPLICATION",
    title: "Worker cancelled application",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "USER_CANCELLED_HIS_SERVICE_SELECTION",
    title: "Worker cancelled selection",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "GET_A_BOOKING_INVITATION_FROM_EMPLOYER",
    title: "Direct booking invitation",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_INVITATION_CANCELLED_BY_EMPLOYER",
    title: "Booking invitation cancelled",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_REQUEST_ACCEPTED_BY_USER",
    title: "Booking accepted",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_REQUEST_REJECTED_BY_USER",
    title: "Booking rejected",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_CANCELLED_BY_EMPLOYER",
    title: "Booking cancelled by employer",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_CANCELLED_BY_USER",
    title: "Booking cancelled by user",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_CANCELLED_BY_MEDIATOR",
    title: "Booking cancelled by mediator",
    audience: "Employer",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "BOOKING_COMPLETED_BY_EMPLOYER",
    title: "Booking completed",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SERVICE_CANCELLED",
    title: "Work cancelled",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SERVICE_CANCELLED_BY_EMPLOYER",
    title: "Work cancelled by employer",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SERVICE_DIRECT_BOOKING_CANCELLED_BY_EMPLOYER",
    title: "Direct booking cancelled",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SERVICE_COMPLETED",
    title: "Work completed",
    audience: "Worker",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SERVICE_COMPLETED_BY_EMPLOYER",
    title: "Work completed by employer",
    audience: "Worker / Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "SERVICE_COMPLETED_AS_MEDIATOR",
    title: "Work completed (mediator)",
    audience: "Mediator",
    trigger: "Immediate",
    category: "Transactional",
  },
  {
    key: "PENDING_REQUEST_REMINDER",
    title: "Pending requests reminder",
    audience: "Worker / Mediator",
    trigger: "Mon/Wed/Fri 10:00 IST",
    category: "Reminder",
  },
  {
    key: "EMPLOYER_PENDING_APPLICATIONS_REMINDER",
    title: "Pending applications reminder",
    audience: "Employer",
    trigger: "Daily 11:00 IST",
    category: "Reminder",
  },
  {
    key: "PENDING_DIRECT_BOOKING_REMINDER",
    title: "Direct booking reminder",
    audience: "Worker / Mediator",
    trigger: "Mon/Wed/Fri 10:30 IST",
    category: "Reminder",
  },
  {
    key: "PAID_SERVICE_PROMOTION",
    title: "Paid service promotion",
    audience: "Employer",
    trigger: "Thu 12:00 IST",
    category: "Promo",
  },
  {
    key: "PROFILE_COMPLETION_REMINDER",
    title: "Profile completion reminder",
    audience: "User",
    trigger: "1st of month 10:00 IST",
    category: "Reminder",
  },
  {
    key: "SYSTEM_ERROR_ALERT",
    title: "System error alert",
    audience: "Admin",
    trigger: "Immediate (throttled)",
    category: "System",
  },
];
