import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Accessibility & Inputs", "A11Y");

export default [
  c({ screenName: "Text to Speech", route: "TextToSpeech", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "On service detail", title: "TTS reads job description aloud", steps: "1. Open service detail.\n2. Tap speaker/TTS.\n3. Listen.", expectedResult: "Job details read in selected language." }),
  c({ screenName: "Text to Speech", route: "TextToSpeech", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "TTS playing", title: "Stop TTS playback", steps: "1. Start TTS.\n2. Tap stop if available.", expectedResult: "Speech stops." }),
  c({ screenName: "Voice to Text", route: "VoiceToText", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Form with voice input", title: "Voice input populates text field", steps: "1. Tap microphone on description field.\n2. Speak.\n3. Observe text.", expectedResult: "Speech converted to text in field.", notes: "Available on add service description step." }),
  c({ screenName: "Selfie Capture", route: "Selfie.tsx", role: ROLES.guest, testType: "Functionality", priority: "P0", prerequisites: "Register step 5; camera permission", title: "Selfie camera capture for profile photo", steps: "1. Open selfie capture.\n2. Take photo.\n3. Confirm.", expectedResult: "Photo preview shown; upload proceeds." }),
  c({ screenName: "Selfie Capture", route: "Selfie.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Gallery option", title: "Pick profile photo from gallery", steps: "1. Choose gallery instead of camera.\n2. Select image.", expectedResult: "Image selected and previewed." }),
  c({ screenName: "Mobile Number Input", route: "MobileNumber.tsx", role: ROLES.guest, testType: "UI Design", priority: "P1", prerequisites: "Login or register", title: "Mobile input shows country code +91", steps: "1. Observe mobile field on login.", expectedResult: "India country code displayed; 10-digit input." }),
  c({ screenName: "Mobile Number Input", route: "MobileNumber.tsx", role: ROLES.guest, testType: "Functionality", priority: "P1", prerequisites: "On login", title: "Mobile input accepts digits only", steps: "1. Try entering letters.", expectedResult: "Non-numeric rejected or filtered." }),
  c({ screenName: "Current Location", route: "CurrentLocation.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Location permission", title: "GPS current location picker", steps: "1. Tap use current location.\n2. Grant permission.", expectedResult: "Coordinates and address populated." }),
  c({ screenName: "View Map", route: "ViewMap.tsx", role: ROLES.all, testType: "Availability", priority: "P1", prerequisites: "Job or user with location", title: "Map view opens for location", steps: "1. Tap view map on service detail.", expectedResult: "Map with marker at location." }),
  c({ screenName: "View Map", route: "ViewMap.tsx", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Map open", title: "Open in Google Maps external app", steps: "1. Tap open in maps if available.", expectedResult: "Google Maps intent opens.", notes: "Uses map.tsx hook." }),
  c({ screenName: "Add Address", route: "addAddress.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Address drawer open", title: "Manual address entry in drawer", steps: "1. Open add address drawer.\n2. Enter address.\n3. Save.", expectedResult: "Address saved to form." }),
  c({ screenName: "Add Address With Location", route: "addAddressWithLocation.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Location drawer", title: "Map pin picker for address", steps: "1. Open location drawer.\n2. Move pin.\n3. Confirm.", expectedResult: "Address from map coordinates saved." }),
  c({ screenName: "Biometric Auth", route: "useBiometricAuth.ts", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Device with fingerprint/face unlock", title: "Biometric auth if wired in UI", steps: "1. Check if biometric prompt appears on login or app open.", expectedResult: "Document whether biometric is wired; if yes, auth succeeds.", notes: "Hook exists; verify UI integration." }),
  c({ screenName: "Date Picker", route: "DateTimePicker", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Add service or booking date field", title: "Android date picker selects date", steps: "1. Tap date field.\n2. Select date on picker.", expectedResult: "Date applied to form." }),
  c({ screenName: "Image Upload", route: "normalizePickedImageUriForUpload.ts", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Image pick flow", title: "Picked image URI normalized for upload", steps: "1. Pick image from gallery.\n2. Upload.", expectedResult: "Upload succeeds without URI errors on Android." }),
  c({ screenName: "Skill Selector", route: "SkillSelector.tsx", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "Skill picker open", title: "Skill selector scroll and multi-select", steps: "1. Open skill selector.\n2. Select multiple skills.", expectedResult: "Skills selectable; list scrolls." }),
  c({ screenName: "Work Requirements Input", route: "WorkRequirements.tsx", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Add service salary step", title: "Worker count and pay numeric inputs", steps: "1. Enter worker count and daily pay.\n2. Verify values.", expectedResult: "Numeric values accepted and saved." }),
  c({ screenName: "Select Role Input", route: "SelectRole.tsx", role: ROLES.guest, testType: "UI Design", priority: "P1", prerequisites: "Register step 4", title: "Role selection cards tappable with clear selection", steps: "1. Tap each role card.", expectedResult: "Selected card highlighted." }),
  c({ screenName: "Picker Input", route: "Picker", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Form with dropdown picker", title: "Android picker wheel selects value", steps: "1. Open picker field.\n2. Select value.", expectedResult: "Value applied to form." }),
  c({ screenName: "Text to Speech", route: "TextToSpeech", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Hindi content", title: "TTS reads Hindi text correctly", steps: "1. Set Hindi.\n2. Open service with Hindi description.\n3. Play TTS.", expectedResult: "Hindi text spoken intelligibly." }),
];
