import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Attendance", "ATT");

export default [
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Availability", priority: "P0", prerequisites: "Employer with active booking", title: "Add attendance screen loads", steps: "1. Navigate to add attendance from booking.", expectedResult: "Attendance form with worker list and date visible." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P0", prerequisites: "On add attendance", title: "Mark worker present for date", steps: "1. Select date.\n2. Mark worker present.\n3. Submit.", expectedResult: "Attendance saved; success toast." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P0", prerequisites: "On add attendance", title: "Mark worker absent for date", steps: "1. Mark worker absent.\n2. Submit.", expectedResult: "Absence recorded." }),
  c({ screenName: "Attendance Component", route: "attendanceComponent.tsx", role: ROLES.employer, testType: "UI Design", priority: "P1", prerequisites: "On add attendance", title: "Present/absent toggle visually clear", steps: "1. Toggle attendance states.", expectedResult: "Clear visual distinction present vs absent." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Multiple workers in booking", title: "Mark attendance for multiple workers same day", steps: "1. Set attendance for each worker.\n2. Submit all.", expectedResult: "All records saved." }),
  c({ screenName: "Show Attendance", route: "/screens/bookings/showAttendance", role: ROLES.employer, testType: "Availability", priority: "P0", prerequisites: "Attendance data exists", title: "Attendance report screen loads", steps: "1. Open show attendance from booking.", expectedResult: "Report with dates and worker attendance visible." }),
  c({ screenName: "Show Attendance", route: "ShowAttendance.tsx", role: ROLES.employer, testType: "Functionality", priority: "P0", prerequisites: "Report with data", title: "Attendance report shows correct present/absent counts", steps: "1. Compare report to submitted data.", expectedResult: "Counts match submitted attendance." }),
  c({ screenName: "Show Attendance", route: "/screens/bookings/showAttendance", role: ROLES.employer, testType: "UI Design", priority: "P1", prerequisites: "Multi-day report", title: "Attendance report calendar/grid readable", steps: "1. Scroll full report.", expectedResult: "Dates and workers aligned; readable on mobile." }),
  c({ screenName: "Side Drawer", route: "GlobalSideDrawer", role: ROLES.employer, testType: "Functionality", priority: "P2", prerequisites: "On attendance view", title: "Side drawer actions on attendance screen", steps: "1. Open side drawer on attendance.\n2. Use available action.", expectedResult: "Drawer action completes expected operation." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "On add attendance", title: "Date picker selects attendance date", steps: "1. Tap date field.\n2. Select date.", expectedResult: "Correct date applied to form." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P2", prerequisites: "Submit without selection", title: "Validation when no attendance marked", steps: "1. Submit empty attendance.", expectedResult: "Validation error or no-op with message." }),
  c({ screenName: "Show Attendance", route: "/screens/bookings/showAttendance", role: ROLES.employer, testType: "UI Design", priority: "P2", prerequisites: "No attendance data", title: "Empty attendance report state", steps: "1. Open report with no records.", expectedResult: "Empty state message." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.worker, testType: "Availability", priority: "P2", prerequisites: "Worker logged in", title: "Worker cannot access add attendance", steps: "1. Attempt add attendance as Worker.", expectedResult: "Not accessible or appropriate restriction." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "UI Design", priority: "P2", prerequisites: "Hindi locale", title: "Attendance labels in Hindi", steps: "1. Set Hindi.\n2. Open add attendance.", expectedResult: "Labels in Hindi." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P2", prerequisites: "Network error on submit", title: "Attendance submit failure shows error", steps: "1. Simulate API failure.\n2. Submit.", expectedResult: "Error toast; data not lost locally if retry supported." }),
  c({ screenName: "Show Attendance", route: "/screens/bookings/showAttendance", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Report open", title: "Back navigation from attendance report", steps: "1. Tap back.", expectedResult: "Returns to booking detail." }),
  c({ screenName: "Add Attendance", route: "/screens/bookings/addAttendance", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Future date", title: "Prevent or warn attendance for future dates if applicable", steps: "1. Select future date.\n2. Attempt submit.", expectedResult: "Validation per business rules." }),
  c({ screenName: "Attendance Component", route: "attendanceComponent.tsx", role: ROLES.employer, testType: "Availability", priority: "P1", prerequisites: "Booking with 5+ workers", title: "Attendance list scrolls for many workers", steps: "1. Open booking with many workers.\n2. Scroll attendance list.", expectedResult: "All workers accessible via scroll." }),
];
