import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Deep Links & Sharing", "DLNK");

export default [
  c({ screenName: "Job Deep Link Bridge", route: "/job/[id]", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "Valid job ID; app installed", title: "Custom scheme apnarojgar://job/id opens service detail", steps: "1. Open apnarojgar://job/<valid-id> via adb or link.\n2. Observe navigation.", expectedResult: "Redirects to /screens/service/[id]." }),
  c({ screenName: "Universal Link", route: "/job/[id]", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "Universal links configured", title: "Universal link https://apnarojgarindia.com/job/id opens app", steps: "1. Tap universal link on Android.\n2. Observe app opens to job detail.", expectedResult: "App opens service detail via job bridge." }),
  c({ screenName: "Service Deep Link", route: "/screens/service/[id]", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Direct service URL", title: "Direct /screens/service/id deep link works", steps: "1. Open apnarojgar://screens/service/<id> if supported.", expectedResult: "Service detail opens." }),
  c({ screenName: "Share Service", route: "shareService.ts", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "On service detail", title: "Share message includes Hindi text and job link", steps: "1. Tap Share on service.\n2. Observe share sheet content.", expectedResult: "Message includes job details and apnarojgar link." }),
  c({ screenName: "Share Service", route: "shareService.ts", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "WhatsApp installed", title: "Share service to WhatsApp", steps: "1. Share → WhatsApp.\n2. Select contact.", expectedResult: "WhatsApp opens with pre-filled Hindi message." }),
  c({ screenName: "Share App", route: "/screens/shareApp", role: ROLES.all, testType: "Availability", priority: "P1", prerequisites: "From profile menu", title: "Share app screen loads with options", steps: "1. Open /screens/shareApp.", expectedResult: "WhatsApp, SMS, LinkedIn, Copy link options visible." }),
  c({ screenName: "Share App WhatsApp", route: "/screens/shareApp", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "WhatsApp installed", title: "Share app via WhatsApp", steps: "1. Tap WhatsApp share.", expectedResult: "WhatsApp opens with app invite message." }),
  c({ screenName: "Share App SMS", route: "/screens/shareApp", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "SMS app available", title: "Share app via SMS", steps: "1. Tap SMS share.", expectedResult: "SMS composer opens with message." }),
  c({ screenName: "Share App LinkedIn", route: "/screens/shareApp", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "LinkedIn installed", title: "Share app via LinkedIn", steps: "1. Tap LinkedIn share.", expectedResult: "LinkedIn share intent opens." }),
  c({ screenName: "Share App Copy Link", route: "/screens/shareApp", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "On share app screen", title: "Copy app link to clipboard", steps: "1. Tap Copy Link.\n2. Paste in notes app.", expectedResult: "App download/link URL copied." }),
  c({ screenName: "Job ID Display", route: "serviceJobId.ts", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "On service detail", title: "Human-readable job ID shown for sharing", steps: "1. Observe job ID on detail or share text.", expectedResult: "Readable job ID included in share content." }),
  c({ screenName: "Deep Link Logged Out", route: "/job/[id]", role: ROLES.guest, testType: "Functionality", priority: "P1", prerequisites: "Logged out", title: "Deep link while logged out redirects to login then job", steps: "1. Log out.\n2. Open job deep link.\n3. Login.", expectedResult: "After login, lands on job detail or prompts login first." }),
  c({ screenName: "Invalid Deep Link", route: "/job/[id]", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Invalid job ID in link", title: "Invalid job deep link shows error", steps: "1. Open apnarojgar://job/invalid.", expectedResult: "Error/not found; no crash." }),
  c({ screenName: "Share App", route: "/screens/shareApp", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Hindi locale", title: "Share app screen in Hindi", steps: "1. Set Hindi.\n2. Open share app.", expectedResult: "Labels in Hindi." }),
  c({ screenName: "Activity Deep Link", route: "/(tabs)/fourth?tab=", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Deep link with tab param", title: "Activity tab deep link with query param", steps: "1. Open link with ?tab=bookings.", expectedResult: "Activity tab opens with bookings sub-tab." }),
];
