import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Global & App Shell", "GLB");

export default [
  c({
    screenName: "App Launch",
    route: "app/_layout.tsx",
    role: ROLES.all,
    testType: "Availability",
    priority: "P0",
    prerequisites: "Fresh install; network available",
    title: "App launches without crash on Android",
    steps:
      "1. Install APK/AAB on Android device.\n2. Tap app icon.\n3. Observe splash and initial screen.",
    expectedResult:
      "App opens without crash; root layout loads; no blank white screen persists.",
  }),
  c({
    screenName: "Force Update",
    route: "ForceUpdateSection",
    role: ROLES.all,
    testType: "Availability",
    priority: "P0",
    prerequisites: "Backend minSupportedVersion > installed app version",
    title: "Force update screen blocks app when version too old",
    steps:
      "1. Set backend minSupportedVersion above current app.\n2. Launch app.\n3. Observe blocking screen.",
    expectedResult:
      "Force update screen shown; user cannot access tabs until updated.",
  }),
  c({
    screenName: "Force Update",
    route: "ForceUpdateSection",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Force update screen visible",
    title: "Update button opens Play Store or update flow",
    steps: "1. On force update screen tap Update/Go to Store.\n2. Observe navigation.",
    expectedResult: "User is directed to app update (Play Store or OTA).",
  }),
  c({
    screenName: "OTA Update",
    route: "InAppUpdatesChecker",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "OTA update available via Expo",
    title: "In-app OTA update check runs after version guard passes",
    steps: "1. Launch app with supported version.\n2. Wait for OTA checker.",
    expectedResult: "OTA prompt shown when update available; no crash if unavailable.",
  }),
  c({
    screenName: "No Internet",
    route: "/screens/placeholders/noInternet",
    role: ROLES.all,
    testType: "Availability",
    priority: "P1",
    prerequisites: "Disable Wi-Fi and mobile data",
    title: "No internet placeholder shown when offline",
    steps: "1. Turn off network.\n2. Open app or trigger API call.\n3. Observe UI.",
    expectedResult: "No internet message/placeholder visible; app does not crash.",
  }),
  c({
    screenName: "No Internet",
    route: "/screens/placeholders/noInternet",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "App showing offline state",
    title: "App recovers when network restored",
    steps: "1. Re-enable network.\n2. Pull to refresh or retry action.",
    expectedResult: "Content loads; offline placeholder dismissed.",
  }),
  c({
    screenName: "Tab Root",
    route: "/(tabs)",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Logged in; on any tab root",
    title: "Hardware back shows exit confirmation at tab root",
    steps: "1. Navigate to any bottom tab root.\n2. Press Android back button.",
    expectedResult: "Exit confirmation modal appears; cancel stays in app; confirm exits.",
  }),
  c({
    screenName: "Auth Guard",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P0",
    prerequisites: "Incomplete profile or logged out",
    title: "Incomplete profile redirects to login or register",
    steps:
      "1. Clear token or use account missing name/address/age/gender.\n2. Attempt to open tabs.",
    expectedResult: "User redirected to /screens/auth/login or register step 2.",
  }),
  c({
    screenName: "Pending Approval",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.all,
    testType: "Availability",
    priority: "P1",
    prerequisites: "Account status not ACTIVE",
    title: "Pending approval user sees profile only without bottom tabs",
    steps: "1. Login with pending/non-ACTIVE account.\n2. Observe layout.",
    expectedResult: "UserProfile full-screen shown; bottom tab bar hidden.",
  }),
  c({
    screenName: "Global Bottom Drawer",
    route: "GlobalBottomDrawer",
    role: ROLES.all,
    testType: "Availability",
    priority: "P1",
    prerequisites: "Screen with filter/address drawer trigger",
    title: "Global bottom drawer opens and closes",
    steps: "1. Open filter or address drawer from listing screen.\n2. Swipe/tap to close.",
    expectedResult: "Drawer slides up with content; closes without UI glitch.",
  }),
  c({
    screenName: "Global Side Drawer",
    route: "GlobalSideDrawer",
    role: ROLES.employer,
    testType: "Availability",
    priority: "P2",
    prerequisites: "Attendance screen accessible",
    title: "Global side drawer available on attendance view",
    steps: "1. Open attendance report screen.\n2. Trigger side drawer action.",
    expectedResult: "Side drawer opens with expected actions.",
  }),
  c({
    screenName: "Toast",
    route: "toast.tsx",
    role: ROLES.all,
    testType: "UI Design",
    priority: "P2",
    prerequisites: "Trigger success and error actions",
    title: "Success and error toasts display correctly",
    steps: "1. Perform action with success response.\n2. Perform action with error.\n3. Observe toasts.",
    expectedResult: "Green success and red error toasts appear briefly and dismiss.",
  }),
  c({
    screenName: "Pull to Refresh",
    route: "List screens",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Any paginated list (home, work, activity)",
    title: "Pull-to-refresh reloads list data",
    steps: "1. Open list screen.\n2. Pull down to refresh.\n3. Observe loader and data.",
    expectedResult: "Refresh indicator shown; list updates with latest data.",
  }),
  c({
    screenName: "Pagination",
    route: "List screens",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "List with more than one page of data",
    title: "Infinite scroll loads next page",
    steps: "1. Scroll to bottom of list.\n2. Wait for loader.\n3. Continue scrolling.",
    expectedResult: "Additional items append; loader disappears when no more data.",
  }),
  c({
    screenName: "Bottom Tabs",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.worker,
    testType: "UI Design",
    priority: "P1",
    prerequisites: "Logged in as Worker",
    title: "Worker tab labels show Home, Work, People, Activity, My Profile",
    steps: "1. Login as Worker.\n2. Observe bottom tab bar labels and icons.",
    expectedResult: "Correct role-specific labels and icons for all 5 tabs.",
  }),
  c({
    screenName: "Bottom Tabs",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.employer,
    testType: "UI Design",
    priority: "P1",
    prerequisites: "Logged in as Employer",
    title: "Employer tab labels show correct role-specific names",
    steps: "1. Login as Employer.\n2. Observe tab bar.",
    expectedResult: "Employer-specific tab labels displayed (e.g. Work shows labour listings context).",
  }),
  c({
    screenName: "Bottom Tabs",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.mediator,
    testType: "UI Design",
    priority: "P1",
    prerequisites: "Logged in as Mediator",
    title: "Mediator tab labels show correct role-specific names",
    steps: "1. Login as Mediator.\n2. Observe tab bar.",
    expectedResult: "Mediator-specific tab labels displayed correctly.",
  }),
  c({
    screenName: "Bottom Tabs",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.admin,
    testType: "UI Design",
    priority: "P1",
    prerequisites: "Logged in as Admin",
    title: "Admin tab labels show Users, Services, People, Requests, Profile",
    steps: "1. Login as Admin.\n2. Observe tab bar labels.",
    expectedResult: "Admin tab labels differ from user roles appropriately.",
  }),
  c({
    screenName: "Notification Badge",
    route: "/(tabs)/_layout.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Unread notifications exist",
    title: "Unread notification badge updates on tab bar",
    steps:
      "1. Ensure unread notifications on server.\n2. Wait up to 30s on tab screen.\n3. Observe badge.",
    expectedResult: "Unread count badge appears/updates on relevant tab or profile icon.",
  }),
  c({
    screenName: "Profile Photo Upload",
    route: "backgroundImageUpload.ts",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Registration with pending photo upload",
    title: "Background profile photo upload retries after registration",
    steps:
      "1. Complete registration with photo.\n2. If upload fails, reopen app.\n3. Check profile photo.",
    expectedResult: "Pending photo upload retries and appears on profile.",
  }),
  c({
    screenName: "Analytics Session",
    route: "AnalyticsSession",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Network available; logged in",
    title: "Analytics session events batch upload",
    steps: "1. Use app for 2+ minutes.\n2. Background and foreground app.\n3. Check network/logs if available.",
    expectedResult: "Session start/foreground/background events queued without crash.",
  }),
  c({
    screenName: "Error Boundary",
    route: "app/_layout.tsx",
    role: ROLES.all,
    testType: "Availability",
    priority: "P2",
    prerequisites: "None",
    title: "Error boundary prevents full app white-screen on component error",
    steps: "1. Navigate through major screens.\n2. Verify no unhandled crash loops.",
    expectedResult: "Isolated errors show fallback UI; app remains usable.",
  }),
  c({
    screenName: "Client Device Headers",
    route: "app/api/index.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "API logging or proxy available",
    title: "API requests include X-Client device headers",
    steps: "1. Perform any authenticated API call.\n2. Inspect request headers.",
    expectedResult: "X-Client-* headers present with platform and version info.",
  }),
  c({
    screenName: "Suspended Account",
    route: "app/api/index.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P0",
    prerequisites: "Account suspended on backend",
    title: "Suspended account shows message and logs out",
    steps: "1. Login or use suspended account.\n2. Trigger API call.",
    expectedResult: "User notified; redirected to login; session cleared.",
  }),
  c({
    screenName: "Disabled Account",
    route: "app/api/index.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P0",
    prerequisites: "Account disabled on backend",
    title: "Disabled account handling same as suspended",
    steps: "1. Use disabled account.\n2. Trigger API call.",
    expectedResult: "Appropriate error shown; user logged out.",
  }),
  c({
    screenName: "Locale Remount",
    route: "app/context/locale.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Logged in",
    title: "Language change remounts app with new strings",
    steps: "1. Change language in settings.\n2. Navigate multiple screens.",
    expectedResult: "All visible strings update to selected language.",
  }),
  c({
    screenName: "Role Remount",
    route: "app/context/locale.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Logged in; role switcher available",
    title: "Role switch remounts app with role-specific UI",
    steps: "1. Switch role via RoleSwitcher.\n2. Observe tabs and home content.",
    expectedResult: "UI updates to match selected role without crash.",
  }),
  c({
    screenName: "Stack Navigation",
    route: "app/_layout.tsx",
    role: ROLES.all,
    testType: "UI Design",
    priority: "P1",
    prerequisites: "Logged in",
    title: "Stack screens show back navigation header",
    steps: "1. Open any /screens/* route from tabs.\n2. Observe header.",
    expectedResult: "Back button/header visible; returns to previous screen.",
  }),
  c({
    screenName: "Deep Link Stack",
    route: "app/_layout.tsx",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Logged in",
    title: "Deep link to /screens/service/[id] works from root stack",
    steps: "1. Open apnarojgar://job/<valid-id> or universal link.\n2. Observe navigation.",
    expectedResult: "Service detail opens without requiring tab navigation first.",
  }),
  c({
    screenName: "Loading States",
    route: "List screens",
    role: ROLES.all,
    testType: "UI Design",
    priority: "P2",
    prerequisites: "Slow network or first load",
    title: "Loading spinners shown during data fetch",
    steps: "1. Open list screen on slow network.\n2. Observe initial load.",
    expectedResult: "Loading indicator visible until data or empty state shown.",
  }),
  c({
    screenName: "Empty States",
    route: "List screens",
    role: ROLES.all,
    testType: "UI Design",
    priority: "P2",
    prerequisites: "Account with no data for list type",
    title: "Empty state message shown when list has no items",
    steps: "1. Open list with zero items (e.g. no bookings).\n2. Observe UI.",
    expectedResult: "Friendly empty state with icon/message; no broken layout.",
  }),
];
