import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Notifications & Push", "NOT");

export default [
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Availability", priority: "P0", prerequisites: "Logged in", title: "Notifications inbox loads", steps: "1. Open /screens/notifications.", expectedResult: "Notification list with title, body, time visible." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "Unread notifications", title: "Mark notification as read on view", steps: "1. Tap unread notification.\n2. Reopen inbox.", expectedResult: "Notification marked read; unread count decreases." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Multiple unread", title: "Mark all as read if option available", steps: "1. Tap Mark All Read.", expectedResult: "All notifications marked read." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Long notification list", title: "Infinite scroll on notifications", steps: "1. Scroll to bottom.", expectedResult: "Older notifications load." }),
  c({ screenName: "Push Registration", route: "usePushNotification.ts", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "Fresh login; notification permission", title: "Push token registered after login", steps: "1. Login.\n2. Grant notification permission.\n3. Verify token on server.", expectedResult: "Device token registered via NOTIFICATION.registerDevice." }),
  c({ screenName: "Push Permission", route: "usePushNotification.ts", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Fresh install", title: "Notification permission prompt on Android", steps: "1. Login first time.\n2. Observe permission dialog.", expectedResult: "Android notification permission requested." }),
  c({ screenName: "Foreground Banner", route: "InAppNotificationBanner", role: ROLES.all, testType: "Availability", priority: "P1", prerequisites: "App in foreground; push received", title: "In-app banner shown for foreground notification", steps: "1. Send push while app open.\n2. Observe banner.", expectedResult: "Banner appears at top with notification content." }),
  c({ screenName: "Notification Tap", route: "NotificationContext.tsx", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "Push with deep link data.url", title: "Tap notification opens deep link URL", steps: "1. Send push with data.url.\n2. Tap notification.", expectedResult: "App navigates to URL target screen." }),
  c({ screenName: "Job Notification", route: "NotificationContext.tsx", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "Push type JOB with job id", title: "Tap JOB notification opens service detail", steps: "1. Send JOB type push.\n2. Tap notification.", expectedResult: "Navigates to /screens/service/[id]." }),
  c({ screenName: "Notification Toast", route: "NotificationToast", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "In-app notification trigger", title: "Notification toast UI styled correctly", steps: "1. Trigger in-app notification toast.", expectedResult: "Toast readable and dismissible." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "No notifications", title: "Notifications empty state", steps: "1. Open inbox with none.", expectedResult: "Empty state message." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "On inbox", title: "Pull to refresh notifications", steps: "1. Pull down.", expectedResult: "Notifications refresh." }),
  c({ screenName: "Unread Badge", route: "/(tabs)/_layout.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Unread count > 0", title: "Unread badge on tab bar updates after read", steps: "1. Note badge count.\n2. Read notifications.\n3. Observe badge.", expectedResult: "Badge count decreases or clears." }),
  c({ screenName: "Android Channel", route: "usePushNotification.ts", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Android 8+", title: "Android notification channel created", steps: "1. Check device notification settings for app.", expectedResult: "Apna Rojgar notification channel exists." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "Mixed read/unread", title: "Unread notifications visually distinct", steps: "1. Observe inbox.", expectedResult: "Unread items have bold/dot/highlight." }),
  c({ screenName: "Local Notifications", route: "useInAppNotifications.tsx", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Unread on server while app open", title: "Local notification triggered for unread while app open", steps: "1. Receive unread while in app.", expectedResult: "Local notification or banner shown." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Hindi locale", title: "Notification inbox labels in Hindi", steps: "1. Set Hindi.\n2. Open inbox.", expectedResult: "Headings in Hindi." }),
  c({ screenName: "Notification Tap", route: "NotificationContext.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "App killed; push received", title: "Tap notification cold-starts app to target", steps: "1. Kill app.\n2. Tap push notification.", expectedResult: "App opens to correct screen." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Offline", title: "Notifications inbox offline handling", steps: "1. Open inbox offline.", expectedResult: "Cached notifications or offline message." }),
  c({ screenName: "Push Registration", route: "usePushNotification.ts", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Permission denied", title: "App functions when notification permission denied", steps: "1. Deny permission.\n2. Use app normally.", expectedResult: "No crash; inbox still works for in-app notifications." }),
  c({ screenName: "Admin Local Notification", route: "triggerNotificationAdmin.tsx", role: ROLES.admin, testType: "Functionality", priority: "P2", prerequisites: "Admin dev trigger if available", title: "Admin local notification trigger for testing", steps: "1. Trigger admin test notification if available.", expectedResult: "Local notification appears.", notes: "Dev/admin feature." }),
  c({ screenName: "Notification Cleanup", route: "cleanUpNotifications.tsx", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Old notifications on device", title: "Stale notifications cleaned up", steps: "1. Accumulate old notifications.\n2. Use app over time.", expectedResult: "Old notifications pruned without crash." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Notification with action", title: "Notification item tap navigates to relevant screen", steps: "1. Tap booking/application notification.", expectedResult: "Opens related booking or service screen." }),
  c({ screenName: "Foreground Banner", route: "InAppNotificationBanner", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Banner visible", title: "Dismiss foreground notification banner", steps: "1. Tap dismiss on banner.", expectedResult: "Banner closes." }),
  c({ screenName: "Notifications Inbox", route: "/screens/notifications", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Long notification text", title: "Long notification body truncates or expands", steps: "1. View notification with long body.", expectedResult: "Readable layout without breaking UI." }),
];
