import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Language & Onboarding", "ONB");

export default [
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "Availability",
    priority: "P0",
    prerequisites: "Fresh install or navigate to /languageSelection",
    title: "Language selection screen loads with language list",
    steps: "1. Open language selection screen.\n2. Observe available languages.",
    expectedResult: "List of supported languages visible (Hindi, English, and regional languages).",
  }),
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P0",
    prerequisites: "On language selection screen",
    title: "Selecting language applies locale and navigates forward",
    steps: "1. Tap a language (e.g. Hindi).\n2. Observe next screen.",
    expectedResult: "App strings switch to selected language; navigates to onboarding or login path.",
  }),
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "UI Design",
    priority: "P1",
    prerequisites: "On language selection screen",
    title: "Language selection UI is readable and tappable on small Android screens",
    steps: "1. Test on small screen device.\n2. Scroll if needed.\n3. Tap each language row.",
    expectedResult: "No text truncation; touch targets adequate; no overlap.",
  }),
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Multiple languages available",
    title: "Each supported locale renders without missing translation keys",
    steps: "1. Select each major language.\n2. Check key screens for raw keys like 'missing.translation'.",
    expectedResult: "No untranslated key strings visible on language selection and next screen.",
  }),
  c({
    screenName: "User Tips / Onboarding",
    route: "/screens/userTipForAppUse",
    role: ROLES.guest,
    testType: "Availability",
    priority: "P1",
    prerequisites: "Navigate to user tips screen",
    title: "Onboarding carousel slides visible",
    steps: "1. Open /screens/userTipForAppUse.\n2. Swipe through slides.",
    expectedResult: "Multiple onboarding slides with images/text visible.",
  }),
  c({
    screenName: "User Tips / Onboarding",
    route: "/screens/userTipForAppUse",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "On onboarding carousel",
    title: "Finish onboarding navigates to main tabs or login",
    steps: "1. Swipe to last slide.\n2. Tap Finish/Get Started.",
    expectedResult: "User navigates to /(tabs) or appropriate auth screen.",
  }),
  c({
    screenName: "User Tips / Onboarding",
    route: "/screens/userTipForAppUse",
    role: ROLES.guest,
    testType: "UI Design",
    priority: "P2",
    prerequisites: "On onboarding carousel",
    title: "Slide indicators and pagination dots visible",
    steps: "1. Swipe between slides.\n2. Observe pagination indicators.",
    expectedResult: "Current slide indicator updates correctly.",
  }),
  c({
    screenName: "Change Language",
    route: "/screens/settings/changeLanguage",
    role: ROLES.all,
    testType: "Availability",
    priority: "P1",
    prerequisites: "Logged in; open from login or profile settings",
    title: "Change language screen accessible from settings and login",
    steps: "1. Profile → Settings → Change Language.\n2. Also test link from login screen.",
    expectedResult: "Language list screen opens from both entry points.",
  }),
  c({
    screenName: "Change Language",
    route: "/screens/settings/changeLanguage",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Logged in with valid token",
    title: "Language change syncs to backend when logged in",
    steps: "1. Change language while logged in.\n2. Kill and reopen app.\n3. Verify language persisted.",
    expectedResult: "Selected language persists locally and on server profile.",
  }),
  c({
    screenName: "Change Language",
    route: "/screens/settings/changeLanguage",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Logged out",
    title: "Language change works locally when logged out",
    steps: "1. From login tap Change Language.\n2. Select new language.\n3. Return to login.",
    expectedResult: "Login screen strings update; no API error shown.",
  }),
  c({
    screenName: "Change Language",
    route: "/screens/settings/changeLanguage",
    role: ROLES.all,
    testType: "UI Design",
    priority: "P2",
    prerequisites: "On change language screen",
    title: "Currently selected language is highlighted",
    steps: "1. Open change language.\n2. Observe selected language marker.",
    expectedResult: "Active language has checkmark or highlight.",
  }),
  c({
    screenName: "Bottom Nav Tutorial",
    route: "/screens/tutorials/bootomNavigation",
    role: ROLES.all,
    testType: "Availability",
    priority: "P2",
    prerequisites: "Tutorial trigger if shown",
    title: "Bottom navigation tutorial overlay displays",
    steps: "1. Trigger bottom nav tutorial if available.\n2. Observe overlay modal.",
    expectedResult: "Tutorial modal explains tab navigation with dismiss option.",
  }),
  c({
    screenName: "Bottom Nav Tutorial",
    route: "/screens/tutorials/bootomNavigation",
    role: ROLES.all,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Tutorial visible",
    title: "Tutorial dismiss closes overlay",
    steps: "1. Open tutorial.\n2. Tap dismiss/close.",
    expectedResult: "Overlay closes; user can interact with tabs.",
  }),
  c({
    screenName: "First Launch",
    route: "useFirstTimeLaunch.tsx",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "Fresh install",
    title: "First launch flow note — auto onboarding may not be wired",
    steps: "1. Fresh install.\n2. Observe if language/onboarding auto-shows.",
    expectedResult: "Document actual behavior; manual navigation to languageSelection works.",
    notes: "useFirstTimeLaunch exists but may not be wired to root nav.",
  }),
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Regional language list",
    title: "Bengali locale selection works",
    steps: "1. Select Bengali (bn).\n2. Verify strings on next screen.",
    expectedResult: "Bengali translations applied.",
  }),
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Regional language list",
    title: "Tamil locale selection works",
    steps: "1. Select Tamil (ta).\n2. Verify strings on next screen.",
    expectedResult: "Tamil translations applied.",
  }),
  c({
    screenName: "Language Selection",
    route: "/languageSelection",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P1",
    prerequisites: "Regional language list",
    title: "Telugu locale selection works",
    steps: "1. Select Telugu (te).\n2. Verify strings on next screen.",
    expectedResult: "Telugu translations applied.",
  }),
  c({
    screenName: "User Tips / Onboarding",
    route: "/screens/userTipForAppUse",
    role: ROLES.guest,
    testType: "Functionality",
    priority: "P2",
    prerequisites: "On onboarding",
    title: "Skip onboarding if skip button present",
    steps: "1. Look for Skip button.\n2. Tap if available.",
    expectedResult: "User proceeds without viewing all slides.",
  }),
];
