import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Tab: People", "PEOP");

export default [
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.worker, testType: "Availability", priority: "P0", prerequisites: "Worker logged in", title: "Worker people tab shows contractors (Mediators)", steps: "1. Open People tab as Worker.", expectedResult: "Contractor/Mediator listings visible." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.employer, testType: "Availability", priority: "P0", prerequisites: "Employer logged in", title: "Employer people tab shows contractors", steps: "1. Open People tab as Employer.", expectedResult: "Contractor listings visible." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.mediator, testType: "Availability", priority: "P0", prerequisites: "Mediator logged in", title: "Mediator people tab shows active work listings", steps: "1. Open People tab as Mediator.", expectedResult: "Active job/service listings visible." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.admin, testType: "Availability", priority: "P1", prerequisites: "Admin logged in", title: "Admin people tab loads", steps: "1. Open People tab as Admin.", expectedResult: "UnifiedPeopleScreen or admin content loads without crash." }),
  c({ screenName: "Contractor List", route: "UnifiedPeopleScreen", role: ROLES.worker, testType: "Functionality", priority: "P0", prerequisites: "Contractors on server", title: "Tap contractor opens user profile", steps: "1. Tap contractor card.", expectedResult: "Navigates to /screens/users/[id]." }),
  c({ screenName: "Active Works List", route: "UnifiedPeopleScreen", role: ROLES.mediator, testType: "Functionality", priority: "P0", prerequisites: "Active jobs on server", title: "Tap active work opens service detail", steps: "1. Tap job card on People tab.", expectedResult: "Navigates to /screens/service/[id]." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "List loaded", title: "Pull to refresh on people tab", steps: "1. Pull down on list.", expectedResult: "List refreshes." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Long list", title: "Pagination on people tab list", steps: "1. Scroll to bottom.", expectedResult: "More items load." }),
  c({ screenName: "Contractor List", route: "UnifiedPeopleScreen", role: ROLES.worker, testType: "UI Design", priority: "P1", prerequisites: "Contractors listed", title: "Contractor cards show team size and skills", steps: "1. Observe contractor cards.", expectedResult: "Team info and skills visible." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.worker, testType: "UI Design", priority: "P1", prerequisites: "Worker on people tab", title: "Section heading indicates contractors", steps: "1. Observe section title.", expectedResult: "Contractors/teams heading shown." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.mediator, testType: "UI Design", priority: "P1", prerequisites: "Mediator on people tab", title: "Section heading indicates active works", steps: "1. Observe section title.", expectedResult: "Active works heading shown." }),
  c({ screenName: "Contractor List", route: "UnifiedPeopleScreen", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Contractor profile open", title: "Send team request to contractor from profile", steps: "1. Open contractor profile.\n2. Send team request if applicable.", expectedResult: "Team request sent successfully." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Empty list", title: "Empty state on people tab", steps: "1. View tab with no contractors/jobs.", expectedResult: "Empty state message shown." }),
  c({ screenName: "Contractor List", route: "allWorkers.tsx", role: ROLES.worker, testType: "Functionality", priority: "P1", prerequisites: "Sort tabs visible", title: "Sort contractors by nearest", steps: "1. Apply nearest sort.", expectedResult: "Contractors sorted by distance." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Hindi locale", title: "People tab strings in Hindi", steps: "1. Set Hindi.\n2. Open people tab.", expectedResult: "Headings in Hindi." }),
  c({ screenName: "Active Works List", route: "UnifiedPeopleScreen", role: ROLES.mediator, testType: "UI Design", priority: "P1", prerequisites: "Jobs listed", title: "Active work cards show pay and workers needed", steps: "1. Observe job cards.", expectedResult: "Pay rate and worker count visible." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "On people tab", title: "Tab icon and label People visible", steps: "1. Observe third tab.", expectedResult: "People tab correctly labeled." }),
  c({ screenName: "Contractor List", route: "UnifiedPeopleScreen", role: ROLES.employer, testType: "Functionality", priority: "P1", prerequisites: "Contractor listed", title: "Like contractor from list or profile", steps: "1. Like a contractor.", expectedResult: "Like status updates." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "On people tab", title: "List scroll performance acceptable", steps: "1. Scroll full list rapidly.", expectedResult: "No major jank or crash." }),
  c({ screenName: "Active Works List", route: "UnifiedPeopleScreen", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Job listed", title: "Apply as mediator from people tab job card path", steps: "1. Open job from people tab.\n2. Apply with team.", expectedResult: "Mediator apply drawer opens from detail." }),
  c({ screenName: "Contractor List", route: "filterWorkers.tsx", role: ROLES.worker, testType: "Functionality", priority: "P2", prerequisites: "Filter available", title: "Filter contractors on people tab", steps: "1. Open filter.\n2. Apply skill filter.", expectedResult: "Contractor list filtered." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.worker, testType: "Functionality", priority: "P2", prerequisites: "Search if available", title: "Search contractors if search entry exists", steps: "1. Use search on people listings.", expectedResult: "Matching contractors shown." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.all, testType: "Availability", priority: "P1", prerequisites: "Offline", title: "People tab handles offline gracefully", steps: "1. Disable network.\n2. Open people tab.", expectedResult: "Offline message or cached data; no crash." }),
  c({ screenName: "Contractor List", route: "UnifiedPeopleScreen", role: ROLES.worker, testType: "UI Design", priority: "P2", prerequisites: "Contractors with photos", title: "Contractor profile photos display correctly", steps: "1. Observe avatar images.", expectedResult: "Photos load or placeholder shown." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.mediator, testType: "Functionality", priority: "P2", prerequisites: "Sort on active works", title: "Sort active works list", steps: "1. Apply sort tab if available.", expectedResult: "Jobs re-ordered." }),
  c({ screenName: "People Tab", route: "/(tabs)/third", role: ROLES.admin, testType: "UI Design", priority: "P2", prerequisites: "Admin on people tab", title: "Admin people tab consistent with app theme", steps: "1. Observe layout and colors.", expectedResult: "Consistent with admin theme." }),
];
