import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Reviews & Ratings", "REV");

export default [
  c({ screenName: "Reviews List", route: "/screens/reviews", role: ROLES.all, testType: "Availability", priority: "P0", prerequisites: "User with reviews", title: "Reviews list screen loads with stats", steps: "1. Open /screens/reviews from profile.", expectedResult: "Average rating, review count, review cards visible." }),
  c({ screenName: "Reviews List", route: "/screens/reviews", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "Reviews exist", title: "Review cards show stars reviewer name and date", steps: "1. Observe review cards.", expectedResult: "Star rating, reviewer, date, text visible." }),
  c({ screenName: "Reviews List", route: "/screens/reviews", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "No reviews", title: "Reviews empty state", steps: "1. Open reviews with none.", expectedResult: "Empty state message." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "Availability", priority: "P0", prerequisites: "Eligible to review user", title: "Add review form loads", steps: "1. Open add review for a user.", expectedResult: "Star selector, reasons, feedback text visible." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "Functionality", priority: "P0", prerequisites: "On add review", title: "Submit review with star rating", steps: "1. Select 5 stars.\n2. Add feedback.\n3. Submit.", expectedResult: "Review saved; success message." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "On add review", title: "Submit review requires star rating", steps: "1. Leave stars empty.\n2. Submit.", expectedResult: "Validation error." }),
  c({ screenName: "Review Reasons", route: "reasons.tsx", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "On add review", title: "Select review reason tags", steps: "1. Tap reason chips.\n2. Submit review.", expectedResult: "Selected reasons saved with review." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Existing review by user", title: "Edit existing review", steps: "1. Open edit review.\n2. Change rating.\n3. Save.", expectedResult: "Review updated on server." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Own review exists", title: "Delete review if option available", steps: "1. Delete review.\n2. Confirm.", expectedResult: "Review removed." }),
  c({ screenName: "Rating Display", route: "RatingAndReviews", role: ROLES.all, testType: "Availability", priority: "P1", prerequisites: "User profile with rating", title: "Rating component on user profile", steps: "1. Open user profile.\n2. Observe rating.", expectedResult: "Average stars and count shown." }),
  c({ screenName: "User Reviews", route: "UserReviews", role: ROLES.all, testType: "Availability", priority: "P2", prerequisites: "Profile with reviews section", title: "Inline reviews on profile overview", steps: "1. View profile reviews section.", expectedResult: "Recent reviews preview shown." }),
  c({ screenName: "Reviews List", route: "/screens/reviews", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Long review list", title: "Reviews list pagination or scroll", steps: "1. Scroll all reviews.", expectedResult: "All reviews accessible." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Hindi locale", title: "Review form labels in Hindi", steps: "1. Set Hindi.\n2. Open add review.", expectedResult: "Labels in Hindi." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "On add review", title: "Star rating tap targets adequate size", steps: "1. Tap each star.", expectedResult: "Stars select reliably on mobile." }),
  c({ screenName: "Reviews List", route: "/screens/reviews", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "On reviews list", title: "Back navigation from reviews", steps: "1. Tap back.", expectedResult: "Returns to profile." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Network error", title: "Review submit failure shows error", steps: "1. Simulate API failure.\n2. Submit.", expectedResult: "Error toast; form data retained." }),
  c({ screenName: "Reviews List", route: "/screens/reviews", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "On reviews", title: "Pull to refresh reviews", steps: "1. Pull down.", expectedResult: "Reviews refresh." }),
  c({ screenName: "Add Review", route: "/screens/reviews/addReview/[id]", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "Long feedback text", title: "Feedback text area supports multiline input", steps: "1. Enter long review text.", expectedResult: "Text wraps; no overflow issues." }),
];
