import { createModuleBuilder, ROLES } from "../helpers.js";

const c = createModuleBuilder("Team / Mediator", "TEAM");

export default [
  c({ screenName: "Team Requests", route: "/screens/teamRequests", role: ROLES.all, testType: "Availability", priority: "P0", prerequisites: "Logged in", title: "Team requests screen loads with received/sent tabs", steps: "1. Open /screens/teamRequests.", expectedResult: "Received and Sent segment tabs visible." }),
  c({ screenName: "Team Requests Received", route: "/screens/teamRequests", role: ROLES.worker, testType: "Functionality", priority: "P0", prerequisites: "Pending team join request", title: "Worker accept team join request", steps: "1. Open Received tab.\n2. Accept request.", expectedResult: "Joined team; request removed." }),
  c({ screenName: "Team Requests Received", route: "/screens/teamRequests", role: ROLES.worker, testType: "Functionality", priority: "P0", prerequisites: "Pending team join request", title: "Worker reject team join request", steps: "1. Reject request.", expectedResult: "Request rejected." }),
  c({ screenName: "Team Requests Sent", route: "/screens/teamRequests", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Sent request pending", title: "Mediator cancel sent team request", steps: "1. Open Sent tab.\n2. Cancel request.", expectedResult: "Request cancelled." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.mediator, testType: "Availability", priority: "P0", prerequisites: "Mediator with team", title: "Team members list loads", steps: "1. Open team detail from profile.", expectedResult: "Team member cards with names and skills." }),
  c({ screenName: "Team Detail", route: "teamDetails.tsx", role: ROLES.mediator, testType: "Functionality", priority: "P0", prerequisites: "Team with members", title: "Mediator remove team member", steps: "1. Tap remove on member.\n2. Confirm.", expectedResult: "Member removed from team." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.worker, testType: "Functionality", priority: "P1", prerequisites: "Worker on a team", title: "Worker leave team", steps: "1. Tap Leave Team.\n2. Confirm.", expectedResult: "Worker removed from team." }),
  c({ screenName: "Send Team Request", route: "useWorkerAction", role: ROLES.worker, testType: "Functionality", priority: "P1", prerequisites: "Worker viewing mediator", title: "Worker send join team request", steps: "1. Open mediator profile.\n2. Send team request.", expectedResult: "Request appears in mediator sent tab." }),
  c({ screenName: "Apply as Mediator", route: "ApplyAsMediatorDrawer", role: ROLES.mediator, testType: "Functionality", priority: "P0", prerequisites: "Mediator with team on job detail", title: "Select subset of team members for job apply", steps: "1. Open apply drawer.\n2. Select some members.\n3. Apply.", expectedResult: "Application includes only selected members." }),
  c({ screenName: "Team Admin Card", route: "TeamAdminCard", role: ROLES.mediator, testType: "UI Design", priority: "P1", prerequisites: "Mediator profile", title: "Team admin card shows member count", steps: "1. Observe team card on profile.", expectedResult: "Member count and team name visible." }),
  c({ screenName: "Team Requests", route: "/screens/teamRequests", role: ROLES.all, testType: "UI Design", priority: "P2", prerequisites: "No requests", title: "Team requests empty state", steps: "1. Open requests with none.", expectedResult: "Empty state on both tabs." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Team detail open", title: "Tap team member opens worker profile", steps: "1. Tap a team member.", expectedResult: "Navigates to /screens/users/[id]." }),
  c({ screenName: "Team Requests", route: "/screens/teamRequests", role: ROLES.all, testType: "Functionality", priority: "P1", prerequisites: "Requests list", title: "Pull to refresh team requests", steps: "1. Pull down on list.", expectedResult: "List refreshes." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.mediator, testType: "UI Design", priority: "P2", prerequisites: "Hindi locale", title: "Team screen labels in Hindi", steps: "1. Set Hindi.\n2. Open team detail.", expectedResult: "Labels in Hindi." }),
  c({ screenName: "Team Requests", route: "ListingVerticalRequests", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "Requests listed", title: "Team request cards show mediator/worker names", steps: "1. Observe request cards.", expectedResult: "Names, date, status visible." }),
  c({ screenName: "Apply as Mediator", route: "ApplyAsMediatorDrawer", role: ROLES.mediator, testType: "UI Design", priority: "P1", prerequisites: "Drawer open", title: "Team member skill mismatch indicated", steps: "1. Open job requiring skill member lacks.", expectedResult: "Mismatch warning or disabled selection." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.mediator, testType: "Functionality", priority: "P2", prerequisites: "Invalid team ID", title: "Invalid team ID error handling", steps: "1. Open invalid team ID.", expectedResult: "Error state; no crash." }),
  c({ screenName: "Team Requests Received", route: "/screens/teamRequests", role: ROLES.worker, testType: "UI Design", priority: "P2", prerequisites: "Multiple requests", title: "Received requests list scroll performance", steps: "1. Scroll many requests.", expectedResult: "Smooth scroll." }),
  c({ screenName: "Mediator Activity", route: "mediatorWorkRequests.tsx", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Mediator work request", title: "Mediator handle work request from activity", steps: "1. Open work request in activity.\n2. Accept/reject.", expectedResult: "Request handled correctly." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.mediator, testType: "Availability", priority: "P1", prerequisites: "Empty team", title: "Empty team state on team detail", steps: "1. Open team with no members.", expectedResult: "Empty state with add/join prompt." }),
  c({ screenName: "Send Team Request", route: "MEDIATOR.sendTeamRequest", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Mediator inviting worker", title: "Mediator send team invite to worker", steps: "1. From worker profile send invite as mediator if available.", expectedResult: "Invite appears in worker received tab." }),
  c({ screenName: "Team Requests", route: "/screens/teamRequests", role: ROLES.all, testType: "Functionality", priority: "P2", prerequisites: "Notification of team request", title: "Team request push opens team requests screen", steps: "1. Tap team request notification.", expectedResult: "Navigates to team requests." }),
  c({ screenName: "Apply as Mediator", route: "ApplyAsMediatorDrawer", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Already applied job", title: "Cannot double-apply same job as mediator", steps: "1. Apply to job.\n2. Attempt apply again.", expectedResult: "Blocked or shows already applied state." }),
  c({ screenName: "Team Detail", route: "/screens/team/[id]", role: ROLES.mediator, testType: "Functionality", priority: "P1", prerequisites: "Team detail", title: "Back navigation from team detail", steps: "1. Tap back.", expectedResult: "Returns to profile." }),
  c({ screenName: "Team Requests", route: "/screens/teamRequests", role: ROLES.all, testType: "UI Design", priority: "P1", prerequisites: "On team requests", title: "Received/Sent tab switch preserves scroll", steps: "1. Scroll received list.\n2. Switch to sent.\n3. Switch back.", expectedResult: "Tabs switch without crash." }),
  c({ screenName: "Team Admin Card", route: "TeamAdminCard", role: ROLES.mediator, testType: "Functionality", priority: "P2", prerequisites: "Team card on profile", title: "Team card tap navigates to team detail", steps: "1. Tap team admin card.", expectedResult: "Opens /screens/team/[id]." }),
  c({ screenName: "Team Requests", route: "/screens/teamRequests", role: ROLES.worker, testType: "Availability", priority: "P1", prerequisites: "Worker not on any team", title: "Worker sent tab empty or hidden appropriately", steps: "1. Open Sent tab as worker.", expectedResult: "Empty or N/A state." }),
  c({ screenName: "Apply as Mediator", route: "ApplyAsMediatorDrawer", role: ROLES.mediator, testType: "Availability", priority: "P0", prerequisites: "Job detail as mediator", title: "Apply as team button visible for mediator", steps: "1. Open job as Mediator.", expectedResult: "Team apply action visible." }),
];
